### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by aymanapatel** [PaperUnicorn/aquamarine#13]
# What
Migrate from Javascript to Typescript

# Why

Typescript is industry standard of maintaining JavaScript projects.

# Possible impact

- **New way of doing things:** This will lead to need to add Tyescript configurations and other unforeseen requirements for writing, building and testing applications.

- **Dynamicaly typed language to statically type language writing:** But given that we use Java in our day jobs we can adapt to using Typescript more easily.
- **Non-Typescript packages:** Since we would be using npm dependencies and many npm packages are still written in JavaScript, this may lead to think on how to better leverage static-typing for such packages. There are ways to do this, which I can document and share later.

**Comment by ChinmayKalegaonakar** [comment]
sorry, I've already made the changes for TS migration in commit e52f66bc6fcf54583e47eb707b658e34cf3d6530 along with TypeORM
